[package]
name = "lux"
version = "0.1.0"
authors = ["Bruno A. Muciño <mucinoab@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
codespan-reporting = "0.11.1"
peekmore = "1.0.0"

[profile.dev]
debug = false
